import turtle

class T:
    def box(self):
        t = turtle.Turtle()
        t.forward(100)      
        t.left(90)         
        t.forward(100)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(100)
        turtle.mainloop()


    def hunman(self):
        h = turtle.Turtle()
        for i in  ['red']:
            h.color(i)
            h.circle(20,360)
            h.right(90)
            h.forward(50)
            h.right(45)
            h.forward(30)
            h.backward(30)
            h.left(70)
            h.forward(30)
            h.backward(30)
            h.right(25)
            h.backward(25)
            h.left(90)
            h.forward(30)
            h.backward(30)
            h.right(180)
            h.forward(30)
            turtle.mainloop()
    
    def fish(self):
        f=turtle.Turtle()
        f.circle(40,360)
        f.right(45)
        f.forward(60)
        f.right(120)
        f.forward(60)
        f.right(110)
        f.forward(60)
        f.penup()
        f.goto(-5,40)
        f.pendown()
        f.right(50)
        f.forward(20)
        f.right(110)
        f.forward(20)
        f.right(130)
        f.forward(20)
        f.penup()
        f.goto(-15,65)
        f.pendown()
        f.dot(10,'black')
        f.penup()
        f.goto(-200,0)
        turtle.mainloop()   

i=T()
i.fish()
